# Generated by Django 2.2.28 on 2022-06-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("katadzuke_app_v1", "0002_roomphoto"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roomphoto",
            old_name="room_photo",
            new_name="photo",
        ),
    ]
