# Generated by Django 2.2.28 on 2022-06-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katadzuke_app_v1', '0006_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_score_photo_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_score_photo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
