# Generated by Django 2.2.28 on 2022-06-11 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("katadzuke_app_v1", "0007_auto_20220611_2356"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_score_room_percent_of_floors",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
