# Generated by Django 2.2.28 on 2022-06-30 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('katadzuke_app_v1', '0012_auto_20220620_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
